[tool.pytest.ini_options]
# directories containing tests
testpaths = ["./src", "./tests"]

# ignore
norecursedirs = ["./venv/", "./cache/", "./.ruff_cache/", "./build/"]

# force pattern for test content
python_files = "*.py"
python_functions = "test_* cli_*"
python_classes = "Test*"

# equivalent to pass the argument to pytest CLI
addopts = [
    # increase verbosity
    "--verbose",
    # same as -s. per-test capturing method: one of fd|sys|no|tee-sys.
    "--capture=no",
    # fail if there are markers not registered in this file
    # "--strict-markers",
    ]

# define all the possible markers
# markers = ["get", "post"]
